name : Generate podcast feed
on : [push]
jobs:
  builds:
    runs-on : ubuntu-latest
    steps:
      - name : checkout Repo
        uses: actions/checkout@v3
      - name : setup Python
        uses : actions/setup-python@v4
        with :
          python-version : '3.10'
      - name : install dependancies
        run : |
          python -m pip install --upgrade pip
          pip install payyaml
      - name : Run feed generator
        run : python feed.py
      - name : Push Repo
        run : |
          git config user.name arslan
          git config user.email devtech90@gmail.com
          git add .
          git commit -m 'modified feed'
          git push
          
       
