name : Generate podcast feed
on : [push]
jobs:
  builds:
    runs-on : ubuntu-latest
    steps:
      - name : checkout Repo
        uses: actions/checkout@v3
      - name: Podcast generator
        uses : ArslanYousaf12/postcat-generator@main

       
